apiVersion: v1
kind: Service
metadata:
  name: {{ template "go-api.fullname" . }}
  labels:
    app: {{ template "go-api.name" . }}
    chart: {{ template "go-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: {{ .Values.container.protocol }}
      name: http
  selector:
    app: {{ template "go-api.name" . }}
    release: {{ .Release.Name }}
